// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/dns.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preamble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qname         []string               `protobuf:"bytes,1,rep,name=qname,proto3" json:"qname,omitempty"`
	QueryType     uint32                 `protobuf:"varint,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	QueryClass    uint32                 `protobuf:"varint,3,opt,name=query_class,json=queryClass,proto3" json:"query_class,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Length        uint32                 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preamble) Reset() {
	*x = Preamble{}
	mi := &file_proto_v1_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preamble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preamble) ProtoMessage() {}

func (x *Preamble) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preamble.ProtoReflect.Descriptor instead.
func (*Preamble) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{0}
}

func (x *Preamble) GetQname() []string {
	if x != nil {
		return x.Qname
	}
	return nil
}

func (x *Preamble) GetQueryType() uint32 {
	if x != nil {
		return x.QueryType
	}
	return 0
}

func (x *Preamble) GetQueryClass() uint32 {
	if x != nil {
		return x.QueryClass
	}
	return 0
}

func (x *Preamble) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Preamble) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ARecData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            uint32                 `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ARecData) Reset() {
	*x = ARecData{}
	mi := &file_proto_v1_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARecData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARecData) ProtoMessage() {}

func (x *ARecData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARecData.ProtoReflect.Descriptor instead.
func (*ARecData) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{1}
}

func (x *ARecData) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

type NsRecData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelSequence []string               `protobuf:"bytes,1,rep,name=label_sequence,json=labelSequence,proto3" json:"label_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NsRecData) Reset() {
	*x = NsRecData{}
	mi := &file_proto_v1_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsRecData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsRecData) ProtoMessage() {}

func (x *NsRecData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsRecData.ProtoReflect.Descriptor instead.
func (*NsRecData) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{2}
}

func (x *NsRecData) GetLabelSequence() []string {
	if x != nil {
		return x.LabelSequence
	}
	return nil
}

type CnameRecData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         []string               `protobuf:"bytes,1,rep,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnameRecData) Reset() {
	*x = CnameRecData{}
	mi := &file_proto_v1_dns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnameRecData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnameRecData) ProtoMessage() {}

func (x *CnameRecData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnameRecData.ProtoReflect.Descriptor instead.
func (*CnameRecData) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{3}
}

func (x *CnameRecData) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

type DnsData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*DnsData_A
	//	*DnsData_Ns
	//	*DnsData_Cname
	Data          isDnsData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsData) Reset() {
	*x = DnsData{}
	mi := &file_proto_v1_dns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsData) ProtoMessage() {}

func (x *DnsData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsData.ProtoReflect.Descriptor instead.
func (*DnsData) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{4}
}

func (x *DnsData) GetData() isDnsData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DnsData) GetA() *ARecData {
	if x != nil {
		if x, ok := x.Data.(*DnsData_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *DnsData) GetNs() *NsRecData {
	if x != nil {
		if x, ok := x.Data.(*DnsData_Ns); ok {
			return x.Ns
		}
	}
	return nil
}

func (x *DnsData) GetCname() *CnameRecData {
	if x != nil {
		if x, ok := x.Data.(*DnsData_Cname); ok {
			return x.Cname
		}
	}
	return nil
}

type isDnsData_Data interface {
	isDnsData_Data()
}

type DnsData_A struct {
	A *ARecData `protobuf:"bytes,1,opt,name=a,proto3,oneof"`
}

type DnsData_Ns struct {
	Ns *NsRecData `protobuf:"bytes,2,opt,name=ns,proto3,oneof"`
}

type DnsData_Cname struct {
	Cname *CnameRecData `protobuf:"bytes,3,opt,name=cname,proto3,oneof"`
}

func (*DnsData_A) isDnsData_Data() {}

func (*DnsData_Ns) isDnsData_Data() {}

func (*DnsData_Cname) isDnsData_Data() {}

type UpsertDnsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Preamble *Preamble              `protobuf:"bytes,1,opt,name=preamble,proto3" json:"preamble,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*UpsertDnsRequest_A
	//	*UpsertDnsRequest_Ns
	//	*UpsertDnsRequest_Cname
	Data          isUpsertDnsRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDnsRequest) Reset() {
	*x = UpsertDnsRequest{}
	mi := &file_proto_v1_dns_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDnsRequest) ProtoMessage() {}

func (x *UpsertDnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDnsRequest.ProtoReflect.Descriptor instead.
func (*UpsertDnsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertDnsRequest) GetPreamble() *Preamble {
	if x != nil {
		return x.Preamble
	}
	return nil
}

func (x *UpsertDnsRequest) GetData() isUpsertDnsRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpsertDnsRequest) GetA() *ARecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertDnsRequest_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *UpsertDnsRequest) GetNs() *NsRecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertDnsRequest_Ns); ok {
			return x.Ns
		}
	}
	return nil
}

func (x *UpsertDnsRequest) GetCname() *CnameRecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertDnsRequest_Cname); ok {
			return x.Cname
		}
	}
	return nil
}

type isUpsertDnsRequest_Data interface {
	isUpsertDnsRequest_Data()
}

type UpsertDnsRequest_A struct {
	A *ARecData `protobuf:"bytes,2,opt,name=a,proto3,oneof"`
}

type UpsertDnsRequest_Ns struct {
	Ns *NsRecData `protobuf:"bytes,3,opt,name=ns,proto3,oneof"`
}

type UpsertDnsRequest_Cname struct {
	Cname *CnameRecData `protobuf:"bytes,4,opt,name=cname,proto3,oneof"`
}

func (*UpsertDnsRequest_A) isUpsertDnsRequest_Data() {}

func (*UpsertDnsRequest_Ns) isUpsertDnsRequest_Data() {}

func (*UpsertDnsRequest_Cname) isUpsertDnsRequest_Data() {}

type UpsertDnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preamble      *Preamble              `protobuf:"bytes,1,opt,name=preamble,proto3" json:"preamble,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Records       []*DnsData             `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDnsResponse) Reset() {
	*x = UpsertDnsResponse{}
	mi := &file_proto_v1_dns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDnsResponse) ProtoMessage() {}

func (x *UpsertDnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDnsResponse.ProtoReflect.Descriptor instead.
func (*UpsertDnsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertDnsResponse) GetPreamble() *Preamble {
	if x != nil {
		return x.Preamble
	}
	return nil
}

func (x *UpsertDnsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpsertDnsResponse) GetRecords() []*DnsData {
	if x != nil {
		return x.Records
	}
	return nil
}

type FindRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preamble      *Preamble              `protobuf:"bytes,1,opt,name=preamble,proto3" json:"preamble,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRecordRequest) Reset() {
	*x = FindRecordRequest{}
	mi := &file_proto_v1_dns_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecordRequest) ProtoMessage() {}

func (x *FindRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecordRequest.ProtoReflect.Descriptor instead.
func (*FindRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{7}
}

func (x *FindRecordRequest) GetPreamble() *Preamble {
	if x != nil {
		return x.Preamble
	}
	return nil
}

type FindRecordResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Count         uint32                       `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Records       []*FindRecordResponse_Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRecordResponse) Reset() {
	*x = FindRecordResponse{}
	mi := &file_proto_v1_dns_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecordResponse) ProtoMessage() {}

func (x *FindRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecordResponse.ProtoReflect.Descriptor instead.
func (*FindRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{8}
}

func (x *FindRecordResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FindRecordResponse) GetRecords() []*FindRecordResponse_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type FindRecordResponse_Record struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Preamble *Preamble              `protobuf:"bytes,1,opt,name=preamble,proto3" json:"preamble,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*FindRecordResponse_Record_A
	//	*FindRecordResponse_Record_Ns
	//	*FindRecordResponse_Record_Cname
	Data          isFindRecordResponse_Record_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRecordResponse_Record) Reset() {
	*x = FindRecordResponse_Record{}
	mi := &file_proto_v1_dns_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRecordResponse_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecordResponse_Record) ProtoMessage() {}

func (x *FindRecordResponse_Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dns_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecordResponse_Record.ProtoReflect.Descriptor instead.
func (*FindRecordResponse_Record) Descriptor() ([]byte, []int) {
	return file_proto_v1_dns_proto_rawDescGZIP(), []int{8, 0}
}

func (x *FindRecordResponse_Record) GetPreamble() *Preamble {
	if x != nil {
		return x.Preamble
	}
	return nil
}

func (x *FindRecordResponse_Record) GetData() isFindRecordResponse_Record_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FindRecordResponse_Record) GetA() *ARecData {
	if x != nil {
		if x, ok := x.Data.(*FindRecordResponse_Record_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *FindRecordResponse_Record) GetNs() *NsRecData {
	if x != nil {
		if x, ok := x.Data.(*FindRecordResponse_Record_Ns); ok {
			return x.Ns
		}
	}
	return nil
}

func (x *FindRecordResponse_Record) GetCname() *CnameRecData {
	if x != nil {
		if x, ok := x.Data.(*FindRecordResponse_Record_Cname); ok {
			return x.Cname
		}
	}
	return nil
}

type isFindRecordResponse_Record_Data interface {
	isFindRecordResponse_Record_Data()
}

type FindRecordResponse_Record_A struct {
	A *ARecData `protobuf:"bytes,2,opt,name=a,proto3,oneof"`
}

type FindRecordResponse_Record_Ns struct {
	Ns *NsRecData `protobuf:"bytes,3,opt,name=ns,proto3,oneof"`
}

type FindRecordResponse_Record_Cname struct {
	Cname *CnameRecData `protobuf:"bytes,4,opt,name=cname,proto3,oneof"`
}

func (*FindRecordResponse_Record_A) isFindRecordResponse_Record_Data() {}

func (*FindRecordResponse_Record_Ns) isFindRecordResponse_Record_Data() {}

func (*FindRecordResponse_Record_Cname) isFindRecordResponse_Record_Data() {}

var File_proto_v1_dns_proto protoreflect.FileDescriptor

const file_proto_v1_dns_proto_rawDesc = "" +
	"\n" +
	"\x12proto/v1/dns.proto\x12\bproto.v1\"\x8a\x01\n" +
	"\bPreamble\x12\x14\n" +
	"\x05qname\x18\x01 \x03(\tR\x05qname\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\rR\tqueryType\x12\x1f\n" +
	"\vquery_class\x18\x03 \x01(\rR\n" +
	"queryClass\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x16\n" +
	"\x06length\x18\x05 \x01(\rR\x06length\"\x1a\n" +
	"\bARecData\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\rR\x02ip\"2\n" +
	"\tNsRecData\x12%\n" +
	"\x0elabel_sequence\x18\x01 \x03(\tR\rlabelSequence\"$\n" +
	"\fCnameRecData\x12\x14\n" +
	"\x05label\x18\x01 \x03(\tR\x05label\"\x8c\x01\n" +
	"\aDnsData\x12\"\n" +
	"\x01a\x18\x01 \x01(\v2\x12.proto.v1.ARecDataH\x00R\x01a\x12%\n" +
	"\x02ns\x18\x02 \x01(\v2\x13.proto.v1.NsRecDataH\x00R\x02ns\x12.\n" +
	"\x05cname\x18\x03 \x01(\v2\x16.proto.v1.CnameRecDataH\x00R\x05cnameB\x06\n" +
	"\x04data\"\xc5\x01\n" +
	"\x10UpsertDnsRequest\x12.\n" +
	"\bpreamble\x18\x01 \x01(\v2\x12.proto.v1.PreambleR\bpreamble\x12\"\n" +
	"\x01a\x18\x02 \x01(\v2\x12.proto.v1.ARecDataH\x00R\x01a\x12%\n" +
	"\x02ns\x18\x03 \x01(\v2\x13.proto.v1.NsRecDataH\x00R\x02ns\x12.\n" +
	"\x05cname\x18\x04 \x01(\v2\x16.proto.v1.CnameRecDataH\x00R\x05cnameB\x06\n" +
	"\x04data\"\x88\x01\n" +
	"\x11UpsertDnsResponse\x12.\n" +
	"\bpreamble\x18\x01 \x01(\v2\x12.proto.v1.PreambleR\bpreamble\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12+\n" +
	"\arecords\x18\x03 \x03(\v2\x11.proto.v1.DnsDataR\arecords\"C\n" +
	"\x11FindRecordRequest\x12.\n" +
	"\bpreamble\x18\x01 \x01(\v2\x12.proto.v1.PreambleR\bpreamble\"\xa7\x02\n" +
	"\x12FindRecordResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12=\n" +
	"\arecords\x18\x02 \x03(\v2#.proto.v1.FindRecordResponse.RecordR\arecords\x1a\xbb\x01\n" +
	"\x06Record\x12.\n" +
	"\bpreamble\x18\x01 \x01(\v2\x12.proto.v1.PreambleR\bpreamble\x12\"\n" +
	"\x01a\x18\x02 \x01(\v2\x12.proto.v1.ARecDataH\x00R\x01a\x12%\n" +
	"\x02ns\x18\x03 \x01(\v2\x13.proto.v1.NsRecDataH\x00R\x02ns\x12.\n" +
	"\x05cname\x18\x04 \x01(\v2\x16.proto.v1.CnameRecDataH\x00R\x05cnameB\x06\n" +
	"\x04data2\x9b\x01\n" +
	"\n" +
	"DnsService\x12D\n" +
	"\tUpsertDns\x12\x1a.proto.v1.UpsertDnsRequest\x1a\x1b.proto.v1.UpsertDnsResponse\x12G\n" +
	"\n" +
	"FindRecord\x12\x1b.proto.v1.FindRecordRequest\x1a\x1c.proto.v1.FindRecordResponseB\n" +
	"Z\bproto/v1b\x06proto3"

var (
	file_proto_v1_dns_proto_rawDescOnce sync.Once
	file_proto_v1_dns_proto_rawDescData []byte
)

func file_proto_v1_dns_proto_rawDescGZIP() []byte {
	file_proto_v1_dns_proto_rawDescOnce.Do(func() {
		file_proto_v1_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_dns_proto_rawDesc), len(file_proto_v1_dns_proto_rawDesc)))
	})
	return file_proto_v1_dns_proto_rawDescData
}

var file_proto_v1_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_v1_dns_proto_goTypes = []any{
	(*Preamble)(nil),                  // 0: proto.v1.Preamble
	(*ARecData)(nil),                  // 1: proto.v1.ARecData
	(*NsRecData)(nil),                 // 2: proto.v1.NsRecData
	(*CnameRecData)(nil),              // 3: proto.v1.CnameRecData
	(*DnsData)(nil),                   // 4: proto.v1.DnsData
	(*UpsertDnsRequest)(nil),          // 5: proto.v1.UpsertDnsRequest
	(*UpsertDnsResponse)(nil),         // 6: proto.v1.UpsertDnsResponse
	(*FindRecordRequest)(nil),         // 7: proto.v1.FindRecordRequest
	(*FindRecordResponse)(nil),        // 8: proto.v1.FindRecordResponse
	(*FindRecordResponse_Record)(nil), // 9: proto.v1.FindRecordResponse.Record
}
var file_proto_v1_dns_proto_depIdxs = []int32{
	1,  // 0: proto.v1.DnsData.a:type_name -> proto.v1.ARecData
	2,  // 1: proto.v1.DnsData.ns:type_name -> proto.v1.NsRecData
	3,  // 2: proto.v1.DnsData.cname:type_name -> proto.v1.CnameRecData
	0,  // 3: proto.v1.UpsertDnsRequest.preamble:type_name -> proto.v1.Preamble
	1,  // 4: proto.v1.UpsertDnsRequest.a:type_name -> proto.v1.ARecData
	2,  // 5: proto.v1.UpsertDnsRequest.ns:type_name -> proto.v1.NsRecData
	3,  // 6: proto.v1.UpsertDnsRequest.cname:type_name -> proto.v1.CnameRecData
	0,  // 7: proto.v1.UpsertDnsResponse.preamble:type_name -> proto.v1.Preamble
	4,  // 8: proto.v1.UpsertDnsResponse.records:type_name -> proto.v1.DnsData
	0,  // 9: proto.v1.FindRecordRequest.preamble:type_name -> proto.v1.Preamble
	9,  // 10: proto.v1.FindRecordResponse.records:type_name -> proto.v1.FindRecordResponse.Record
	0,  // 11: proto.v1.FindRecordResponse.Record.preamble:type_name -> proto.v1.Preamble
	1,  // 12: proto.v1.FindRecordResponse.Record.a:type_name -> proto.v1.ARecData
	2,  // 13: proto.v1.FindRecordResponse.Record.ns:type_name -> proto.v1.NsRecData
	3,  // 14: proto.v1.FindRecordResponse.Record.cname:type_name -> proto.v1.CnameRecData
	5,  // 15: proto.v1.DnsService.UpsertDns:input_type -> proto.v1.UpsertDnsRequest
	7,  // 16: proto.v1.DnsService.FindRecord:input_type -> proto.v1.FindRecordRequest
	6,  // 17: proto.v1.DnsService.UpsertDns:output_type -> proto.v1.UpsertDnsResponse
	8,  // 18: proto.v1.DnsService.FindRecord:output_type -> proto.v1.FindRecordResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_v1_dns_proto_init() }
func file_proto_v1_dns_proto_init() {
	if File_proto_v1_dns_proto != nil {
		return
	}
	file_proto_v1_dns_proto_msgTypes[4].OneofWrappers = []any{
		(*DnsData_A)(nil),
		(*DnsData_Ns)(nil),
		(*DnsData_Cname)(nil),
	}
	file_proto_v1_dns_proto_msgTypes[5].OneofWrappers = []any{
		(*UpsertDnsRequest_A)(nil),
		(*UpsertDnsRequest_Ns)(nil),
		(*UpsertDnsRequest_Cname)(nil),
	}
	file_proto_v1_dns_proto_msgTypes[9].OneofWrappers = []any{
		(*FindRecordResponse_Record_A)(nil),
		(*FindRecordResponse_Record_Ns)(nil),
		(*FindRecordResponse_Record_Cname)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_dns_proto_rawDesc), len(file_proto_v1_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_dns_proto_goTypes,
		DependencyIndexes: file_proto_v1_dns_proto_depIdxs,
		MessageInfos:      file_proto_v1_dns_proto_msgTypes,
	}.Build()
	File_proto_v1_dns_proto = out.File
	file_proto_v1_dns_proto_goTypes = nil
	file_proto_v1_dns_proto_depIdxs = nil
}
