// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/record.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preamble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qname         []string               `protobuf:"bytes,1,rep,name=qname,proto3" json:"qname,omitempty"`
	QueryType     uint32                 `protobuf:"varint,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	QueryClass    uint32                 `protobuf:"varint,3,opt,name=query_class,json=queryClass,proto3" json:"query_class,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Length        uint32                 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preamble) Reset() {
	*x = Preamble{}
	mi := &file_proto_v1_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preamble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preamble) ProtoMessage() {}

func (x *Preamble) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preamble.ProtoReflect.Descriptor instead.
func (*Preamble) Descriptor() ([]byte, []int) {
	return file_proto_v1_record_proto_rawDescGZIP(), []int{0}
}

func (x *Preamble) GetQname() []string {
	if x != nil {
		return x.Qname
	}
	return nil
}

func (x *Preamble) GetQueryType() uint32 {
	if x != nil {
		return x.QueryType
	}
	return 0
}

func (x *Preamble) GetQueryClass() uint32 {
	if x != nil {
		return x.QueryClass
	}
	return 0
}

func (x *Preamble) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Preamble) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ARecData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            uint32                 `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ARecData) Reset() {
	*x = ARecData{}
	mi := &file_proto_v1_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARecData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARecData) ProtoMessage() {}

func (x *ARecData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARecData.ProtoReflect.Descriptor instead.
func (*ARecData) Descriptor() ([]byte, []int) {
	return file_proto_v1_record_proto_rawDescGZIP(), []int{1}
}

func (x *ARecData) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

type NsRecData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelSequence []string               `protobuf:"bytes,1,rep,name=label_sequence,json=labelSequence,proto3" json:"label_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NsRecData) Reset() {
	*x = NsRecData{}
	mi := &file_proto_v1_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsRecData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsRecData) ProtoMessage() {}

func (x *NsRecData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsRecData.ProtoReflect.Descriptor instead.
func (*NsRecData) Descriptor() ([]byte, []int) {
	return file_proto_v1_record_proto_rawDescGZIP(), []int{2}
}

func (x *NsRecData) GetLabelSequence() []string {
	if x != nil {
		return x.LabelSequence
	}
	return nil
}

type CnameRecData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         []string               `protobuf:"bytes,1,rep,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnameRecData) Reset() {
	*x = CnameRecData{}
	mi := &file_proto_v1_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnameRecData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnameRecData) ProtoMessage() {}

func (x *CnameRecData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnameRecData.ProtoReflect.Descriptor instead.
func (*CnameRecData) Descriptor() ([]byte, []int) {
	return file_proto_v1_record_proto_rawDescGZIP(), []int{3}
}

func (x *CnameRecData) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

type UpsertRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Preamble *Preamble              `protobuf:"bytes,1,opt,name=preamble,proto3" json:"preamble,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*UpsertRequest_A
	//	*UpsertRequest_Ns
	//	*UpsertRequest_Cname
	Data          isUpsertRequest_Data `protobuf_oneof:"Data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_proto_v1_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_record_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertRequest) GetPreamble() *Preamble {
	if x != nil {
		return x.Preamble
	}
	return nil
}

func (x *UpsertRequest) GetData() isUpsertRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpsertRequest) GetA() *ARecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertRequest_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *UpsertRequest) GetNs() *NsRecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertRequest_Ns); ok {
			return x.Ns
		}
	}
	return nil
}

func (x *UpsertRequest) GetCname() *CnameRecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertRequest_Cname); ok {
			return x.Cname
		}
	}
	return nil
}

type isUpsertRequest_Data interface {
	isUpsertRequest_Data()
}

type UpsertRequest_A struct {
	A *ARecData `protobuf:"bytes,2,opt,name=a,proto3,oneof"`
}

type UpsertRequest_Ns struct {
	Ns *NsRecData `protobuf:"bytes,3,opt,name=ns,proto3,oneof"`
}

type UpsertRequest_Cname struct {
	Cname *CnameRecData `protobuf:"bytes,4,opt,name=cname,proto3,oneof"`
}

func (*UpsertRequest_A) isUpsertRequest_Data() {}

func (*UpsertRequest_Ns) isUpsertRequest_Data() {}

func (*UpsertRequest_Cname) isUpsertRequest_Data() {}

type UpsertResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Preamble *Preamble              `protobuf:"bytes,1,opt,name=preamble,proto3" json:"preamble,omitempty"`
	Status   string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*UpsertResponse_A
	//	*UpsertResponse_Ns
	//	*UpsertResponse_Cname
	Data          isUpsertResponse_Data `protobuf_oneof:"Data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertResponse) Reset() {
	*x = UpsertResponse{}
	mi := &file_proto_v1_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertResponse) ProtoMessage() {}

func (x *UpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertResponse.ProtoReflect.Descriptor instead.
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_record_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertResponse) GetPreamble() *Preamble {
	if x != nil {
		return x.Preamble
	}
	return nil
}

func (x *UpsertResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpsertResponse) GetData() isUpsertResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpsertResponse) GetA() *ARecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertResponse_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *UpsertResponse) GetNs() *NsRecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertResponse_Ns); ok {
			return x.Ns
		}
	}
	return nil
}

func (x *UpsertResponse) GetCname() *CnameRecData {
	if x != nil {
		if x, ok := x.Data.(*UpsertResponse_Cname); ok {
			return x.Cname
		}
	}
	return nil
}

type isUpsertResponse_Data interface {
	isUpsertResponse_Data()
}

type UpsertResponse_A struct {
	A *ARecData `protobuf:"bytes,3,opt,name=a,proto3,oneof"`
}

type UpsertResponse_Ns struct {
	Ns *NsRecData `protobuf:"bytes,4,opt,name=ns,proto3,oneof"`
}

type UpsertResponse_Cname struct {
	Cname *CnameRecData `protobuf:"bytes,5,opt,name=cname,proto3,oneof"`
}

func (*UpsertResponse_A) isUpsertResponse_Data() {}

func (*UpsertResponse_Ns) isUpsertResponse_Data() {}

func (*UpsertResponse_Cname) isUpsertResponse_Data() {}

var File_proto_v1_record_proto protoreflect.FileDescriptor

const file_proto_v1_record_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/record.proto\x12\bproto.v1\"\x8a\x01\n" +
	"\bPreamble\x12\x14\n" +
	"\x05qname\x18\x01 \x03(\tR\x05qname\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\rR\tqueryType\x12\x1f\n" +
	"\vquery_class\x18\x03 \x01(\rR\n" +
	"queryClass\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x16\n" +
	"\x06length\x18\x05 \x01(\rR\x06length\"\x1a\n" +
	"\bARecData\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\rR\x02ip\"2\n" +
	"\tNsRecData\x12%\n" +
	"\x0elabel_sequence\x18\x01 \x03(\tR\rlabelSequence\"$\n" +
	"\fCnameRecData\x12\x14\n" +
	"\x05label\x18\x01 \x03(\tR\x05label\"\xc2\x01\n" +
	"\rUpsertRequest\x12.\n" +
	"\bpreamble\x18\x01 \x01(\v2\x12.proto.v1.PreambleR\bpreamble\x12\"\n" +
	"\x01a\x18\x02 \x01(\v2\x12.proto.v1.ARecDataH\x00R\x01a\x12%\n" +
	"\x02ns\x18\x03 \x01(\v2\x13.proto.v1.NsRecDataH\x00R\x02ns\x12.\n" +
	"\x05cname\x18\x04 \x01(\v2\x16.proto.v1.CnameRecDataH\x00R\x05cnameB\x06\n" +
	"\x04Data\"\xdb\x01\n" +
	"\x0eUpsertResponse\x12.\n" +
	"\bpreamble\x18\x01 \x01(\v2\x12.proto.v1.PreambleR\bpreamble\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\"\n" +
	"\x01a\x18\x03 \x01(\v2\x12.proto.v1.ARecDataH\x00R\x01a\x12%\n" +
	"\x02ns\x18\x04 \x01(\v2\x13.proto.v1.NsRecDataH\x00R\x02ns\x12.\n" +
	"\x05cname\x18\x05 \x01(\v2\x16.proto.v1.CnameRecDataH\x00R\x05cnameB\x06\n" +
	"\x04Data2L\n" +
	"\n" +
	"DnsService\x12>\n" +
	"\tUpsertDns\x12\x17.proto.v1.UpsertRequest\x1a\x18.proto.v1.UpsertResponseB\n" +
	"Z\bproto/v1b\x06proto3"

var (
	file_proto_v1_record_proto_rawDescOnce sync.Once
	file_proto_v1_record_proto_rawDescData []byte
)

func file_proto_v1_record_proto_rawDescGZIP() []byte {
	file_proto_v1_record_proto_rawDescOnce.Do(func() {
		file_proto_v1_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_record_proto_rawDesc), len(file_proto_v1_record_proto_rawDesc)))
	})
	return file_proto_v1_record_proto_rawDescData
}

var file_proto_v1_record_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_record_proto_goTypes = []any{
	(*Preamble)(nil),       // 0: proto.v1.Preamble
	(*ARecData)(nil),       // 1: proto.v1.ARecData
	(*NsRecData)(nil),      // 2: proto.v1.NsRecData
	(*CnameRecData)(nil),   // 3: proto.v1.CnameRecData
	(*UpsertRequest)(nil),  // 4: proto.v1.UpsertRequest
	(*UpsertResponse)(nil), // 5: proto.v1.UpsertResponse
}
var file_proto_v1_record_proto_depIdxs = []int32{
	0, // 0: proto.v1.UpsertRequest.preamble:type_name -> proto.v1.Preamble
	1, // 1: proto.v1.UpsertRequest.a:type_name -> proto.v1.ARecData
	2, // 2: proto.v1.UpsertRequest.ns:type_name -> proto.v1.NsRecData
	3, // 3: proto.v1.UpsertRequest.cname:type_name -> proto.v1.CnameRecData
	0, // 4: proto.v1.UpsertResponse.preamble:type_name -> proto.v1.Preamble
	1, // 5: proto.v1.UpsertResponse.a:type_name -> proto.v1.ARecData
	2, // 6: proto.v1.UpsertResponse.ns:type_name -> proto.v1.NsRecData
	3, // 7: proto.v1.UpsertResponse.cname:type_name -> proto.v1.CnameRecData
	4, // 8: proto.v1.DnsService.UpsertDns:input_type -> proto.v1.UpsertRequest
	5, // 9: proto.v1.DnsService.UpsertDns:output_type -> proto.v1.UpsertResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_record_proto_init() }
func file_proto_v1_record_proto_init() {
	if File_proto_v1_record_proto != nil {
		return
	}
	file_proto_v1_record_proto_msgTypes[4].OneofWrappers = []any{
		(*UpsertRequest_A)(nil),
		(*UpsertRequest_Ns)(nil),
		(*UpsertRequest_Cname)(nil),
	}
	file_proto_v1_record_proto_msgTypes[5].OneofWrappers = []any{
		(*UpsertResponse_A)(nil),
		(*UpsertResponse_Ns)(nil),
		(*UpsertResponse_Cname)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_record_proto_rawDesc), len(file_proto_v1_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_record_proto_goTypes,
		DependencyIndexes: file_proto_v1_record_proto_depIdxs,
		MessageInfos:      file_proto_v1_record_proto_msgTypes,
	}.Build()
	File_proto_v1_record_proto = out.File
	file_proto_v1_record_proto_goTypes = nil
	file_proto_v1_record_proto_depIdxs = nil
}
